import datetime
from datetime import timezone

import httplib2
from oauth2client import file as file_, client, tools
import pytz
from googleapiclient import discovery
from dateutil import parser
from googleapiclient.errors import HttpError
from i3pystatus.calendar import CalendarBackend, CalendarEvent, formatter
from i3pystatus.core.util import user_open, require, internet


SCOPES = 'https://www.googleapis.com/auth/calendar.readonly'


class GoogleCalendarEvent(CalendarEvent):
    def __init__(self, google_event):
        self.id = google_event['id']
        self.title = google_event['summary']
        self.start = self._parse_date(google_event['start'])
        self.end = self._parse_date(google_event['end'])
        self.recurring = 'recurringEventId' in google_event
        self._link = google_event['htmlLink']
        self._status = google_event['status']
        self._kind = google_event['kind']

    @formatter
    def htmlLink(self):
        pass

    @formatter
    def status(self):
        pass

    @formatter
    def kind(self):
        pass

    def _parse_date(self, date_section):
        pass


class Google(CalendarBackend):
    """
    Calendar backend for interacting with Google Calendar.

    Requires the Google Calendar API package - https://developers.google.com/google-apps/calendar/quickstart/python.
    Additionally requires the `colour`, `httplib2`, `oauth2client`, `pytz`, `google-api-python-client` and `dateutil` modules.

    The first time this module is ran, you will need to specify the location of `credentials.json` (as credentials_json)
    acquired from: https://developers.google.com/google-apps/calendar/quickstart/python
    this will open a browser window for auth, and save a token to `credential_path`. you will need to reload i3poystatus
    afterwards

    If you already have a token `credentials_json` is not required (though highly recommended incase your token gets broken)

    .. rubric:: Available formatters

    * `{kind}` â€” type of event
    * `{status}` â€” eg, confirmed
    * `{htmlLink}` â€” link to the calendar event
    """

    settings = (
        ('credential_path', 'Path to save credentials to (auto generated the first time this module is ran)'),
        ('credentials_json', 'path to credentials.json (generated by google)'),
        ('days', 'Only show events between now and this many days in the future'),
    )

    required = ('credential_path',)

    credentials_json = None
    days = 7

    def init(self):
        pass

    @require(internet)
    def update(self):
        pass

    def on_click(self, event):
        pass

    def connect_service(self):
        pass

    def refresh_events(self):
        """
        Retrieve the next N events from Google.
        """
        pass

    def get_timerange_formatted(self, now):
        """
        Return two ISO8601 formatted date strings, one for timeMin, the other for timeMax (to be consumed by get_events)
        """
        pass
